// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkVJY0MvyLuQ_IRcr08Tc8JZ4Pouk2S8o',
    appId: '1:497287726063:web:8c1c4389513a2048de2c1a',
    messagingSenderId: '497287726063',
    projectId: 'demoapp-e39b5',
    authDomain: 'demoapp-e39b5.firebaseapp.com',
    storageBucket: 'demoapp-e39b5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlLLtIhX4M3sN332GEVBMbBYJ3zLbfSpM',
    appId: '1:497287726063:android:9b74e33e3e554a22de2c1a',
    messagingSenderId: '497287726063',
    projectId: 'demoapp-e39b5',
    storageBucket: 'demoapp-e39b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7OmvPitsjb7VLL2sH-Shik-TvYGiRdhY',
    appId: '1:497287726063:ios:6d5665cfec060003de2c1a',
    messagingSenderId: '497287726063',
    projectId: 'demoapp-e39b5',
    storageBucket: 'demoapp-e39b5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7OmvPitsjb7VLL2sH-Shik-TvYGiRdhY',
    appId: '1:497287726063:ios:6d5665cfec060003de2c1a',
    messagingSenderId: '497287726063',
    projectId: 'demoapp-e39b5',
    storageBucket: 'demoapp-e39b5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkVJY0MvyLuQ_IRcr08Tc8JZ4Pouk2S8o',
    appId: '1:497287726063:web:b86cc453848c48f8de2c1a',
    messagingSenderId: '497287726063',
    projectId: 'demoapp-e39b5',
    authDomain: 'demoapp-e39b5.firebaseapp.com',
    storageBucket: 'demoapp-e39b5.firebasestorage.app',
  );
}
